### ISSUE TITLE
Incompatibily with macOS & `ipfs v0.11.x`

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [SomajitDey/ipfs-chat#23]
whenever I try to run it the program exits with `Error: Failed to launch IPFS daemon` and I cannot for the life of me get it to run successfully.

**Comment by SomajitDey** [comment]
Hi @343GuiltySpark-04. A few queries:

1. Is this happening right after installing `ipfs -chat`, or did it run alright in your system before?
2. `ipfs version` info
3. What happens when you do `ipfs daemon`?

**Comment by notclement** [comment]
# 1
I got ```Error: Failed to launch IPFS daemon``` as well
![image](https://user-images.githubusercontent.com/19283318/157454520-e66c49c5-3965-4772-8f34-01f762647df9.png)


# 2
I am running ipfs version ```0.11.0```
![image](https://user-images.githubusercontent.com/19283318/157454183-18bc2963-c77c-446c-b5ea-d3e3a0deae30.png)

# 3
Things are working fine when i run ```ipfs daemon``` on its own
I am able to use ```ipfs add <file>```
![image](https://user-images.githubusercontent.com/19283318/157454338-1092fde5-7b95-4d3c-a4ab-bcf8a11a93d7.png)

**Comment by 343GuiltySpark-04** [comment]
> Hi @343GuiltySpark-04. A few queries:
> 
> 1. Is this happening right after installing `ipfs -chat`, or did it run alright in your system before?
> 2. `ipfs version` info
> 3. What happens when you do `ipfs daemon`?

sorry for the late reply, been super busy with school. ill try and find some time later today to start up the laptop and pull that info for you.

**Comment by SomajitDey** [comment]
Hi @notclement and @343GuiltySpark-04, 

Thanks a lot for reporting. 

Although I am aware of some breaking changes that `ipfs v0.11` brought from `v0.10` (which `ipfs-chat` was originally coded on) regarding relays and pubsub, I couldn't reproduce your issue (i.e. daemon not launching) on my system. In any case, it seems an overhaul is necessary to align `ipfs-chat` with `ipfs v0.11` and onwards.

Unfortunately it would take me some time to fix things, as I have just moved to a new city with a new full-time research-job. I'd let you know through this thread when updates arrive. I sincerely regret the inconvenience.

P.S. @notclement Seems like you are using macOS, hence the error with `du`.

**Comment by SomajitDey** [comment]
@343GuiltySpark-04 are you using macOS, like @notclement ? 

I forgot to mention earlier that `ipfs-chat` was tested on Linux and not macOS. Some commands take different options in Linux and macOS, and some commands, e.g. `flock`, are present only in Linux. The code that launches `ipfs daemon` for `ipfs-chat` depends on `flock` and hence fails in macOS.
