### ISSUE TITLE
It is possible to web port?

### ISSUE THREAD

**Issue by savethekiddes** [SomajitDey/ipfs-chat#24]
I don't want any kind extensive support, adknowledging that one of the strong point of ipfs-chat is to be a barebone bash script without any kind of nonsense, but is theoretically possible to port it to a web interface? My question is, there is anything strictly tied to the operating system that makes impossible to get it running it on a browser?

**Comment by SomajitDey** [comment]
@savethekiddes a web interface is certainly possible. See [this](https://github.com/SomajitDey/ipfs-chat/discussions/12#discussion-3528856) discussion for example.

**Comment by savethekiddes** [comment]
Sorry for duplicating the post.
